name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 24.x

      - name: Install dependencies
        run: mix deps.get

      - name: Run Credo
        run: mix credo --strict

      - name: Run tests
        run: mix test
